---
ID: "a7d74a88-99eb-4989-adcc-63fe9e895d89"
Parent: "b7156de1-5ea6-4291-a497-2adf1b9e67aa"
Template: "b7156de1-5ea6-4291-a497-2adf1b9e67aa"
Path: /sitecore/templates/Feature/SF/PushNotifications/Component Templates/Subscribe Button/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200401T160146Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
