---
ID: "74e2b1ad-6f29-48c6-9b78-02e3c9c60c79"
Parent: "1132c14a-ac64-4397-bcc1-55ba9fac57f2"
Template: "1132c14a-ac64-4397-bcc1-55ba9fac57f2"
Path: /sitecore/templates/Feature/SF/PushNotifications/Rendering Parameters/Subscribe Button Rendering Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: __Standard Values
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151021T125358Z
